
 - name: cleanup old packages
   ansible.builtin.command: pkg autoremove -y

 - name: update packages
   ansible.builtin.command: pkg upgrade -y

 - name: clean packages
   ansible.builtin.command: pkg clean -y
