
- name: cleanup old packages
  ansible.builtin.shell:
    cmd: pkg autoremove -y

- name: update packages
  ansible.builtin.shell:
    cmd: pkg upgrade -y

- name: clean packages
  ansible.builtin.shell:
    cmd: pkg clean -y
